PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX ogc: <http://www.opengis.net/ont/geosparql#>
PREFIX geom: <http://geovocab.org/geometry#>
PREFIX lgdo: <http://linkedgeodata.org/ontology/>

SELECT ?l ?lon ?lat
FROM <http://linkedgeodata.org> {
  ?s
    a lgdo:Amenity ;
    rdfs:label ?l ;
    geom:geometry [
      ogc:asWKT ?g
    ] .
FILTER( REGEX(?l, "(pharmacy|chemist)", "i")) .
FILTER(bif:st_intersects (?g, bif:st_point (0.51476085186004639, 51.382572174072266), 1.5)) .
FILTER( REGEX(str(?g), "point", "i")) .
BIND(STRBEFORE(STRAFTER(str(?g), "POINT("), " ") AS ?lon) .
BIND(STRAFTER(STRBEFORE(str(?g), ")"), " ") AS ?lat)
}
